-- AlterTable
ALTER TABLE "LogEntry" ADD COLUMN     "kcal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "serving_size" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "serving_weight" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_carbs" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_fat" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_protein" DOUBLE PRECISION NOT NULL DEFAULT 0;
